<a href="https://colab.research.google.com/github/nirmalaraj77/Python/blob/main/Python_Game.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import NumPy and Pandas
import numpy as np
import pandas as pd

# Create first_array 3r 7c
first_array = np.array([['A', 'B', 'C', 'D', 'E', 'F', 'G'],
                      ['H', 'I', 'J', 'K', 'L','M', 'N'],
                      ['O', 'P', 'Q', 'R', 'S', 'T', 'U']])

# Reshape first array 7r 3c
first_array_reshape = first_array.reshape(7,3)
print ("\n This is first layout")
print(first_array_reshape)

# Input Choice
while True:
    try:
        x = int (input ('Think of a letter and input the column the letter is in: 1, 2 or 3 : '))
        if x < 1 or x >= 4:
            raise ValueError #this will send it to the print message and back to the input option
        break
    except ValueError:
        print("Invalid choice. The number must be 1, 2 or 3")


# Create second array with if-else-elif and value of x
if x == 1:
  # Col index 0 in middle
  second_array = np.array([first_array_reshape[:, 1], first_array_reshape [:, 0], first_array_reshape [:, 2]])
  
elif x == 2:
   # Col index 1 in middle
   second_array = np.array([first_array_reshape[:, 0], first_array_reshape [:, 1], first_array_reshape [:, 2]])
    
else :
   # Col index 2 in middle
   second_array = np.array([first_array_reshape[:, 0], first_array_reshape [:, 2], first_array_reshape [:, 1]])


# Reshape second array 7r 3c
second_array_reshape = second_array.reshape(7,3)
print ("\n This is the second layout")
print(second_array_reshape)

# Input Choice
while True:
    try:
        x = int (input ('Input the column the letter you thought of is in: 1, 2 or 3 : '))
        if x < 1 or x >= 4:
            raise ValueError #this will send it to the print message and back to the input option
        break
    except ValueError:
        print("Invalid choice. The number must be 1, 2 or 3")


# Create third array with if-else-elif and value of x
if x == 1:
  # Col index 0 in middle
  third_array = np.array([second_array_reshape0[:, 1], second_array_reshape [:, 0], second_array_reshape [:, 2]])
  
elif x == 2:
   # Col index 1 in middle
   third_array = np.array([second_array_reshape[:, 0], second_array_reshape [:, 1], second_array_reshape [:, 2]])
    
else :
   # Col index 2 in middle
   third_array = np.array([second_array_reshape[:, 0], second_array_reshape [:, 2], second_array_reshape [:, 1]])


# Reshape third array 7r 3c
third_array_reshape = third_array.reshape(7,3)
print ("\n This is the third layout")
print(second_array_reshape)








 This is first layout
[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']
 ['J' 'K' 'L']
 ['M' 'N' 'O']
 ['P' 'Q' 'R']
 ['S' 'T' 'U']]


In [ ]:




# Define function to create array of 21 values with x subset in middle 
def create_array (my_array, x=2) :
  """Define function to create and reshape arrays of 21 values based on x"""
  if x == 1: # 1 in middle
    arr = np.array([my_arr[7:14], my_arr[:7], my_arr [14:]])

  elif x == 2: # 2 in middle
    arr = np.array([my_arr[:7], my_arr[7:14], my_arr [14:]])

  else : # 3 in middle
    arr = np.array([my_arr[:7], my_arr[14:], my_arr [14:]])

    return arr



# Create first array from my_arr by calling function, x = 2 is default
firstarr = create_array (my_arr)

# Reshape firstarr
firstre = firstarr.reshape(7,3)







# Reshape firstre and pass to firstreshape
firstreshape = firstre.reshape (3, 7)


# Flatten firstreshape and pass to firstreshapeflatten
firstreshapeflatten = firstreshape.flatten()
print (firstreshapeflatten)

# Create second array by calling function
secondarr = create_array (firstre, x)

# Reshape firstarr
secondre = secondarr.reshape(7,3)

# Print first layout
print ("\n This is the secons layout")
print (secndre)

AttributeError: ignored

In [ ]:
t= np.array([[ 0., -1.,  0.,  0.],
           [ 0.,  1.,  1.,  1.],
           [ 0.,  0., -1.,  0.],
          [ 0.,  0.,  0., -1.]])


t[[0, 1]] = t[[1, 0]] # will swap the first two columns:

print (t)

[[ 0.  1.  1.  1.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]
