<a href="https://colab.research.google.com/github/nirmalaraj77/Python/blob/main/Python_Notes_DataCamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Functions and Packages

##Functions
### - Call with round brackets
### - Functions save results to variables
### - Syntax: output = function_name(input)
### - Help syntax: help (function-name) or ? function_name

##Methods
### - Call with Dot . after data type name
### - Each object has associated attribute and methods
### - Call help to find methods associated with data types

##Packages
### - Import packages as libraries, alias or selective

In [ ]:
# Import Library   
import math 

# Import Library as alias   
import numpy as np  
import matplotlib.pyplot as plt

# Selective import  
from math import pi
from scipy.linalg import inv as my_inv

#Variables and Data Types

##Assign Variables

In [11]:
# Assign variable
x = 5
y = 7

# Assign variable # Cleaner Code
a, b, c = 1, 2, 3

# Assign variable to variable
d = a 
print (a, b, c, d)

# Changing variable does not change original value
d = 5
print (a, b, c, d)

1 2 3 1
1 2 3 5


## Calculate Variables 
### - Arithmetic operations highest to lowest

In [12]:
x ** y # Exponent
x % y # Modulus 
x // y # Integer division 
x / y # Division  
x * y # Multiply  
x - y # Substract   
x + y # Sum

12

## Type Conversion

In [14]:
# Variable to String, Integer, Float and Boolean  
str('5'), 
str(2.444)  
str('Manual')  
int (1)  
int (2.7)  
int (True)   
float (5)  
float ('1.7')  
bool (True)  
bool (False)  
bool (1)  
bool(0)  
bool ('Amma@')

True

##String Operations

In [17]:
my_string = 'This String is Awesome' # Assign variable to string 

print (my_string * 3) # Multiply string

print (my_string + my_string) # Add strings (without spaces)

print (my_string, my_string) # Add strings (adds a space) # Cleaner Code

print (my_string + ' ' + 'is it not so?') # Add other strings

print(my_string, ' ', 'is this new method?') # Add other strings # Cleaner Code 

This String is AwesomeThis String is AwesomeThis String is Awesome
This String is AwesomeThis String is Awesome
This String is Awesome This String is Awesome
This String is Awesome is it not so?
This String is Awesome   is this new method?


##String Indexing, Subsetting and Slicing  
### - Place index in square brackets [ ] 
### - Index starts at 0
### - Use Colon : to slice
### - Slicing Syntax: string [start : end]
### - **Start index is included, end index is excluded**
### - No need to include index if slicing from first or last element
### - Start and end indexes are included if denoted with colons : 



In [37]:
my_string = '0123456789' #Assign string 

print (my_string [2]) # Character index 3 

print (my_string [6 : 9]) # Start index 6 is inclided, end index 9 not included 

print (my_string[: 3]) # Start index included from beginning (used :). End index 3 not included

print (my_string [7 :]) # Start index 7 incuded. Indexes until end included (used :) 

print (my_string [-3]) # Select 3rd from last element

2
678
012
789
7


##String Methods and Functions
### - Call methods with dot. and round brackets after ( )
### - Call functions with function name and round brackets 

In [18]:
my_string = '  this string is awesome  ' # Assign string with whitespaces front and after

print (len(my_string)) # String length

print (('y' in my_string)) # Boolean for string character

print (my_string.upper ()) # Uppercase

print (my_string.lower ()) # Lowercase

print (my_string.capitalize ()) # Capitalize 1st Character

print (my_string.title ()) # Capitalise all words

print (my_string.count ('s')) # Count String Element

print (my_string.replace ('s', 'X')) # Replace all occuarances of String Element with another

print (my_string.strip ()) # Strip Whitespaces beginning and end

26
False
  THIS STRING IS AWESOME  
  this string is awesome  
  this string is awesome  
  This String Is Awesome  
4
  thiX Xtring iX aweXome  
this string is awesome


#Lists

##Create List 
### - Use square brackets [ ]
### - Can have different Types

In [30]:
# Assign variables # Cleaner Code
hall, kit, liv, bed, bath, w,x, y, z = 11.25, 18.0, 20.0, 10.75, 9.5, 'Amman', True, 1>2, 10001

# Create list areas with variables of different data types
areas = [hall, kit, liv, bed, bath, w, x, y, z] 
print (areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 'Amman', True, False, 10001]


##List Methods

In [36]:
# Assign variables # Cleaner Code
a, b, c, d  = 'My', 5, 1.25, 1 >2

# Create List
my_list = [a, b, c, d]  

my_list.append (' !!!') # Append Elemets one by one
my_list.append (5/10) # Append Elements one by one 
print (my_list) 

my_list.remove(5) # Remove Element
print (my_list)

# Create another list
my_list2 = [8, 9, 10, 1, 5, -1]

# Reverse List Order
my_list2.reverse() 
print (my_list2)

# Extend my_list with all elements of my_list2
my_list.extend (my_list2)
print (my_list)

['My', 5, 1.25, False, ' !!!', 0.5]
['My', 1.25, False, ' !!!', 0.5]
[-1, 5, 1, 10, 9, 8]
['My', 1.25, False, ' !!!', 0.5, -1, 5, 1, 10, 9, 8]


##List of Lists
### - Can be any number of lists

In [ ]:
# Area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# House information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

print (house)
print (type (house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


##List Indexing, Subsetting and Slicing
### - Place index in square brackets [ ] 
### - Index starts at 0
### - Use Colon : to slice
### - Slicing Syntax: list [start : end]
### - **Start index is included, end index is excluded**
### - No need to include index if slicing from first or last element
### - Start and end indexes are included if denoted with colons : 


In [38]:
# Create list
l = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
print (l [4]) # Print 4th index 

a = 'is'; b = 'nice'; my_list = ['my', 'list', 'xxx', a, b] # Create List # Cleaner Code
print (my_list [1]) # Print 2nd element 
print (my_list [-2]) # Print 2nd to last item from end

l = ['a' ,'b', 'c', 'd', 'e'] # Create list
print (l [1:3]) # Select elements 2-3 # Start index 1 is included, end index 3 is excluded
print (l [2:]) # Select elemets 3 - end # Start index 2 is included, end is denoted by colon : 
print (l [:2]) # Select elements start - 2 # Start index denoted by colon :, end index 2 is exluded 

4
list
is
['b', 'c']
['c', 'd', 'e']
['a', 'b']


##Copy List
### - Copying a list will point to same list
### - Create new copy with list() or : for seperate list 
### - With Indexing / Slicing / Subsetting
### - Result is new list with selected elements


In [ ]:
l = ['p', 'q', 'r', 's', 't'] # Create list
l_copy = l # Create copy
del l_copy [2] # Delete index item in copy
print (l) # Original also changes
print (l_copy) # Because both point to same list

l = ['p', 'q', 'r', 's', 't'] # Create list
l1 = list (l) # Copy all indexes to new list with list()
l2 = l [:3] # # Copy index start - 2  to new list
print (l1)
print (l2)

['p', 'q', 's', 't']
['p', 'q', 's', 't']
['p', 'q', 'r', 's', 't']
['p', 'q', 'r']


##Subset List of Lists
### - Use square brackets [ ] 
### - Same rules for indexing and slicing  

In [ ]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]] # Create list of lists

x = [["a", "b", "c"], # Create list of lists # Cleaner Code
     ["d", "e", "f"],
     ["g", "h", "i"]] 

print (my_list [1][2]) 
print (my_list [0] [3:]) 
print (x[2] [0]) 
print (x[2] [:2])
print (x[1] [-2])

8
[4, 5]
g
['g', 'h']
e


##Replace List Elements

In [ ]:
x = ["a", "b", "c", "d"] # Create List
x[1] = "r" # Replace index 1  
x[2:] = ["s", "t"] # Replace index 2 - end
print (x)

['a', 'r', 's', 't']


##Extend List

In [ ]:
x = ["a", "b", "c", "d"] # Create list
y = x + ["e", "f"] # Add elements
print (y)

print (y + y) # Add list to list
print (y * 5) # Multiply list

['a', 'b', 'c', 'd', 'e', 'f']
['a', 'b', 'c', 'd', 'e', 'f', 'a', 'b', 'c', 'd', 'e', 'f']
['a', 'b', 'c', 'd', 'e', 'f', 'a', 'b', 'c', 'd', 'e', 'f', 'a', 'b', 'c', 'd', 'e', 'f', 'a', 'b', 'c', 'd', 'e', 'f', 'a', 'b', 'c', 'd', 'e', 'f']


##Delete List Elements

In [ ]:
x = ["a", "b", "c", "d"] # Create list
del(x[1]) # Delete 1st index element
print (x)

['a', 'c', 'd']


##List Methods

In [ ]:
z = ['my', 'list', 'is', 'is', 'nice'] # Create List

print (z.index ('is')) # Get the first index of an item

print (z.count ('is')) # Count an item

z.append ('!!!') # Append an item at a time
print (z)

z.remove ('is') # Remove an item at a time
print (z)

z = ['my', 'list', 'is', 'is', 'nice'] # Create List for following exercises

del (z [-2]) # Remove items by indexing / slicing / subsetting
print (z)
       
z.extend ('2') # Extend list
print (z)

z.pop (-1) # Remove index item
print (z)

z.insert (-1, 'NOT') # Insert an item before index position
print (z)

z.sort() # Sort list
print (z)

z.sort (reverse = True) # Reverse Sort
print (z)

z.reverse () # Reverse list # Cleaner Code
print (z)

2
2
['my', 'list', 'is', 'is', 'nice', '!!!']
['my', 'list', 'is', 'nice', '!!!']
['my', 'list', 'is', 'nice']
['my', 'list', 'is', 'nice', '2']
['my', 'list', 'is', 'nice']
['my', 'list', 'is', 'NOT', 'nice']
['NOT', 'is', 'list', 'my', 'nice']
['nice', 'my', 'list', 'is', 'NOT']
['NOT', 'is', 'list', 'my', 'nice']


#Numpy Arrays and 2D Numpy Arrays
### - Creates a n-dimensional array (ndarray)
### - Can create array of any dimensions  
### - CAN ONLY CONTAIN ONE DATA TYPE
### - Including different types will coerce array to stringsto end up with homogenous array
### - Syntax : np.array()
### - Multi-demensional arrays work like improved list of lists
### - Calculate element wide vector arithmentics
### - Advanced index, select and subset element wide
### - **Start index is included, end index is excluded**
### - Create boolen np arrays
### - Index, Slice and Subset ork the dame way as Python Lists
### - NP attributes are called with dot. but are not methods (no round brackets after)
### - Combine matrices with single numbers, vectors, and with other matrices







In [ ]:
baseball = [180, 215, 210, 210, 188, 176, 209, 200] # Create list baseball

import numpy as np # Import the numpy package as np

np_baseball_cm = np.array(baseball) # Create a NumPy array for heights in centimetres from baseball: np_baseball_cm

print(type(np_baseball)) # Print out type of np_baseball

np_baseball_in = np_baseball_cm * 0.394 # Create np array np_baseball_in by multiplying np_baseball_cm by 0.394
print (np_baseball_in)

np_baseball_in_small = np_baseball_in < 80.00 # Create boolean numpy array np_baseball_in_small of players less than 80 in tall
print (np_baseball_in_small) # Boolena numpy array
print (np_baseball_in [np_baseball_in_small]) # Select / filter small palyers from array


np_2d = np.array ([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, 68.7]]) # Create 2d np array
print (np_2d)
print(np_2d.shape) # Use dot. shape attrubute. Shape is 2 rows, 5 columns


np_2d = np.array ([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, 68.7]]) # Create 2d np array
print (np_2d [0] [2]) # Subset Row 0, Index 2 : 1.71
print (np_2d [0, 2]) # Subset Row 0, Index 2 : 1.71 # Cleaner Code
print (np_2d [:, 1:3 ]) # Subset all Rows with Colon :, and after comma, subset Columns 2 - 3 with 1:3  (3rd index not included)
print (np_2d [1, :]) # Subset Row 2 with index 1, after comma, subset All columns with colon :

np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]]) # Create 2D np array
print (np_mat * 2) # 2D arithmetic

np_mat_new = np_mat + np.array([10, 5]) # Add 10 to 1st element and 5 to 2nd elements in each array 
print (np_mat_new)

print (np_mat + np_mat) # Add element to element matrice wise 

<class 'numpy.ndarray'>
[70.92  84.71  82.74  82.74  74.072 69.344 82.346 78.8  ]
[ True False False False  True  True False  True]
[70.92  74.072 69.344 78.8  ]
[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]
(2, 5)
1.71
1.71
[[ 1.68  1.71]
 [59.2  63.6 ]]
[65.4 59.2 63.6 88.4 68.7]
[[ 2  4]
 [ 6  8]
 [10 12]]
[[11  7]
 [13  9]
 [15 11]]
[[ 2  4]
 [ 6  8]
 [10 12]]


#Numpy Statistics
### - Use Numpy Functions

In [ ]:
import numpy as np # Import Numpy
x = np.array ([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, 68.7]]) # Create 2d np array

print (x) # Print array 

print (x.shape) # Array shape, 2 rows and 5 columns

print (np.mean (x [0, :])) # Mean / Average of 1st row, all columns

print (np.median(x [1, :])) # Median of 2nd row, all columns

print (np.std (x [:, 0])) # Standard Deviation on All Rows, 1st colummn

print (np.corrcoef (x [0, :], x [1:, :])) # Correlation between 1st and 2nd rows, All columns

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]
(2, 5)
1.7600000000000002
65.4
31.835000000000004
[[1.         0.97514969]
 [0.97514969 1.        ]]


In [ ]:
url = 'https://raw.githubusercontent.com/nirmalaraj77/Python/main/fifa.csv' # Load fifa.csv from github public url 

import pandas as pd # Import Pandas package

df = pd.read_csv (url) # Create Pandas data Frame df from fifa.csv

df # Load DataFrame













id                        100264
 name            Tomasz Szewczuk
 rating                       57
 position                      A
 height                      185
 foot                      Right
 rare                          0
 pace                         65
 shooting                     54
 passing                      43
 dribbling                    53
 defending                    55
 heading                      74
 diving                         
 handling                       
 kicking                        
 reflexes                       
 speed                          
 positioning                 NaN
Name: 2, dtype: object

In [ ]:
positions = df['position'].tolist() # Convert the 'position' column of the DataFrame to a list 'positions

KeyError: ignored